# Generated by Django 3.2.9 on 2021-11-28 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(verbose_name='商品ID')),
                ('seller_id', models.IntegerField(verbose_name='卖家ID')),
                ('buyer_id', models.IntegerField(verbose_name='买家ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('number', models.IntegerField(default=0, verbose_name='数量')),
                ('sum_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True, verbose_name='总价')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(verbose_name='商品ID')),
                ('commenter_id', models.IntegerField(verbose_name='评论者ID')),
                ('content', models.TextField(max_length=1000, verbose_name='评论内容')),
                ('comment_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('status', models.BooleanField(default=True, verbose_name='评论状态')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='用户名')),
                ('password', models.CharField(max_length=28, verbose_name='密码')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='邮箱')),
                ('money', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='余额')),
                ('check_number', models.CharField(default=0, max_length=4, verbose_name='验证码')),
                ('sex', models.CharField(max_length=10, verbose_name='性别')),
                ('img', models.ImageField(default='default.jpg', upload_to='user_avatar/', verbose_name='头像')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_img', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='item_img/', verbose_name='商品图片')),
                ('item_name', models.CharField(blank=True, default='NULL', max_length=100, null=True, verbose_name='商品名')),
                ('item_introduction', models.TextField(blank=True, default='这是一个商品的介绍需要十五个字', max_length=1000, null=True, verbose_name='商品介绍')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('seller_id', models.IntegerField(verbose_name='卖家ID')),
                ('number', models.IntegerField(blank=True, default=0, null=True, verbose_name='库存')),
                ('item_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True, verbose_name='价格')),
            ],
        ),
        migrations.CreateModel(
            name='ReComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment_id', models.IntegerField(verbose_name='回复ID')),
                ('commenter_id', models.IntegerField(verbose_name='回复者ID')),
                ('content', models.TextField(max_length=1000, verbose_name='回复内容')),
                ('comment_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='卖家昵称')),
                ('password', models.CharField(max_length=28, verbose_name='密码')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='邮箱')),
                ('register_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='注册时间')),
                ('img', models.ImageField(default='default.jpg', upload_to='seller_avatar/', verbose_name='头像')),
                ('sex', models.CharField(max_length=10, verbose_name='性别')),
                ('check_number', models.CharField(default='0', max_length=4, verbose_name='验证码')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.goods')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('number', models.IntegerField(default=0, verbose_name='数量')),
                ('sum_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True, verbose_name='订单价格')),
                ('status', models.IntegerField(choices=[(0, '下单未处理'), (1, '接受'), (2, '不接受'), (3, '运输中'), (4, '已收货')], default=0, verbose_name='订单状态')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.customer', verbose_name='买家ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.goods', verbose_name='商品ID')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='goods',
            field=models.ManyToManyField(through='app1.Order', to='app1.Goods'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200, verbose_name='地址')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.customer', verbose_name='用户ID')),
            ],
        ),
    ]
