# Generated by Django 3.2.9 on 2021-12-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='category_id',
            field=models.IntegerField(choices=[(0, '无分类'), (1, '生活用品'), (2, '体育用品'), (3, '学习用品'), (4, '小吃零食'), (5, '服装'), (6, '电子产品')], default=0, verbose_name='商品分类'),
        ),
    ]
