# Generated by Django 3.2.9 on 2021-12-10 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ReComment',
            field=models.OneToOneField(default=-1, on_delete=django.db.models.deletion.CASCADE, to='app1.recomment', verbose_name='回复ID'),
        ),
    ]
