# Generated by Django 3.2.9 on 2021-12-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20211210_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='sex',
            field=models.IntegerField(choices=[(0, '男'), (1, '女'), (2, '其他')], default=0, verbose_name='性别'),
        ),
    ]
