# Generated by Django 3.2.9 on 2021-12-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_seller_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(default='customer_avatar/default.jpg', upload_to='user_avatar/', verbose_name='头像'),
        ),
    ]
